name: Run Pandas Dataframe

On:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    cron: '0 0 * * *'

jobs:
  run_pandas_jon:
    runs-on: ubunto-latest
  steps:
  - name: checkout code
    uses: actions/checkout@v2
  - name: install python
    uses: actions/setup-python@v4
  - name: install dependencies
    uses: pip install pandas 
  - name: run app 
    uses: python app.py 